(()=>{
  const bg=document.getElementById('starfield');
  const bctx=bg.getContext('2d');
  let stars=[];let last=0;
  function resizeBg(){const d=Math.min(devicePixelRatio||1,2);bg.width=innerWidth*d;bg.height=innerHeight*d;bg.style.width=innerWidth+'px';bg.style.height=innerHeight+'px';bctx.setTransform(d,0,0,d,0,0);const count=Math.min(360,Math.floor(innerWidth*innerHeight/5200));stars=Array.from({length:count},(_,i)=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.35+.15,a:Math.random()*.75+.15,s:Math.random()*.25+.03,p:i%7===0}));}
  function drawBg(t){if(t-last>32){last=t;bctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){const tw=.7+.3*Math.sin(t*.0007+s.x);bctx.globalAlpha=s.a*tw;bctx.fillStyle=s.p?'#8adfff':'#ffffff';bctx.beginPath();bctx.arc(s.x,s.y,s.r,0,Math.PI*2);bctx.fill();}bctx.globalAlpha=1;}requestAnimationFrame(drawBg)}
  addEventListener('resize',resizeBg);resizeBg();requestAnimationFrame(drawBg);

  window.DQUniverse={data:null,canvas:null,ctx:null,anim:null,setData(data){this.data=data;this.drawLoop()},init(){this.canvas=document.getElementById('universeCanvas');if(!this.canvas)return;this.ctx=this.canvas.getContext('2d');const ro=new ResizeObserver(()=>this.resize());ro.observe(this.canvas);this.resize();this.drawLoop()},resize(){if(!this.canvas)return;const r=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,r.width*d);this.canvas.height=Math.max(1,r.height*d);this.ctx.setTransform(d,0,0,d,0,0);},drawLoop(){if(this.anim)return;const tick=t=>{this.draw(t);this.anim=requestAnimationFrame(tick)};this.anim=requestAnimationFrame(tick)},draw(t){if(!this.canvas||!this.ctx)return;const r=this.canvas.getBoundingClientRect(),w=r.width,h=r.height,c=this.ctx;c.clearRect(0,0,w,h);const atom=this.data?.atom||{level:1,energy:.3,radius:36};const cx=w*.48,cy=h*.44,base=Math.min(atom.radius||36,82);const glow=c.createRadialGradient(cx,cy,0,cx,cy,base*4);glow.addColorStop(0,'rgba(95,236,255,.17)');glow.addColorStop(.38,'rgba(104,70,255,.07)');glow.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=glow;c.beginPath();c.arc(cx,cy,base*4,0,Math.PI*2);c.fill();
      const molecules=this.data?.molecules||[];molecules.forEach((m,i)=>{const a=t*.00003*(i%2?1:-1)+i*(Math.PI*2/Math.max(1,molecules.length));const rr=base*3.0+18*(i%3);const x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr*.52;c.strokeStyle='rgba(108,185,255,.12)';c.beginPath();c.moveTo(cx,cy);c.lineTo(x,y);c.stroke();c.fillStyle='rgba(103,248,255,.70)';c.beginPath();c.arc(x,y,3+Math.min(7,(m.mass||1)*.3),0,Math.PI*2);c.fill();c.fillStyle='rgba(200,230,255,.72)';c.font='10px system-ui';c.fillText(String(m.name).slice(0,24),x+9,y+3)});
      for(let j=0;j<3;j++){c.save();c.translate(cx,cy);c.rotate(j*1.02+t*.00012*(j%2?1:-1));c.scale(1,.45+.08*j);c.strokeStyle=j===1?'rgba(157,123,255,.35)':'rgba(103,248,255,.28)';c.beginPath();c.ellipse(0,0,base*2.1,base*2.1,0,0,Math.PI*2);c.stroke();const a=t*.0012*(j%2?1:-1)+j*2.1;c.fillStyle='#eaffff';c.shadowBlur=12;c.shadowColor='#67f8ff';c.beginPath();c.arc(Math.cos(a)*base*2.1,Math.sin(a)*base*2.1,4,0,Math.PI*2);c.fill();c.restore();}
      c.shadowBlur=28;c.shadowColor='#67f8ff';const g=c.createRadialGradient(cx-base*.25,cy-base*.25,2,cx,cy,base);g.addColorStop(0,'#e6ffff');g.addColorStop(.18,'#67f8ff');g.addColorStop(.53,'#6252dc');g.addColorStop(1,'#140a35');c.fillStyle=g;c.beginPath();c.arc(cx,cy,base,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='#fff';c.textAlign='center';c.font=`700 ${Math.max(12,base*.37)}px system-ui`;c.fillText('DQ',cx,cy+5);c.textAlign='start';
      const peers=this.data?.peers||[];peers.forEach((p,i)=>{const a=i*2.4+.5,x=w*.82+Math.cos(a)*35,y=h*.22+Math.sin(a)*30;c.fillStyle='rgba(157,123,255,.65)';c.beginPath();c.arc(x,y,8,0,Math.PI*2);c.fill();});
    }};
  addEventListener('DOMContentLoaded',()=>window.DQUniverse.init());
})();
