"""Sensor backends: how readings of the world enter the scientific core.

A backend is an adapter, nothing more. It knows how to talk to one instrument
and hands back plain `SensorReading` values; it does not store anything, does
not decide what a reading means, and has no access to the experiment record.

The mock backend
----------------
`MockCartSensor` generates data from a kinematic model. It exists so the whole
pipeline can be exercised - and so the reference experiment can be run on a
machine with no hardware attached - and it is therefore the single most
dangerous object in this package: realistic-looking numbers that came from an
equation rather than from a cart.

So `simulated` is not a flag a caller sets. It is fixed by the backend class,
`MockCartSensor.simulated` is True and cannot be turned off, and readings from
it carry SIMULATED provenance all the way into storage, where
`Measurement.evidence_kind` reports SIMULATION rather than MEASUREMENT. There
is no path through this module that turns generated data into a measurement of
the world.
"""
from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass, field
from typing import Any, Iterator, Sequence

from science.models import Provenance, ProvenanceKind
from science.units import Quantity, parse_unit


class SensorError(RuntimeError):
    """Raised when a backend cannot produce a reading."""


@dataclass(frozen=True)
class SensorReading:
    """One value from one instrument, before it enters the record."""

    quantity: str
    value: float
    unit: str
    uncertainty: float | None = None
    timestamp: float = field(default_factory=time.time)
    sensor_id: str = ""
    simulated: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not str(self.quantity).strip():
            raise SensorError("A reading must name the quantity it measures")
        parse_unit(self.unit)  # fail here, not during analysis
        if self.uncertainty is not None and float(self.uncertainty) < 0:
            raise SensorError("Reading uncertainty cannot be negative")

    @property
    def as_quantity(self) -> Quantity:
        return Quantity.of(self.value, self.unit, self.uncertainty)

    @property
    def provenance(self) -> Provenance:
        """SIMULATED for generated data, SENSOR for an instrument.

        Derived from `simulated` rather than stored alongside it, so the two
        cannot drift apart.
        """
        kind = ProvenanceKind.SIMULATED if self.simulated else ProvenanceKind.SENSOR
        return Provenance(kind, agent=self.sensor_id or "unknown-sensor",
                          notes="Generated by a model, not measured." if self.simulated else "")

    def as_dict(self) -> dict[str, Any]:
        return {
            "quantity": self.quantity,
            "value": self.value,
            "unit": self.unit,
            "uncertainty": self.uncertainty,
            "timestamp": self.timestamp,
            "sensor_id": self.sensor_id,
            "simulated": self.simulated,
            "metadata": dict(self.metadata),
        }


class SensorBackend:
    """Interface every sensor adapter implements.

    Subclasses override `available`, `describe` and `read`. Reporting
    unavailability honestly matters more than working: a backend that cannot
    reach its hardware must say so rather than return a plausible number.
    """

    name: str = "sensor"
    simulated: bool = False

    def available(self) -> tuple[bool, str]:
        """(usable, reason). The reason is shown to the user when False."""
        raise NotImplementedError

    def describe(self) -> dict[str, Any]:
        """What this backend measures, so a caller can decide before reading."""
        raise NotImplementedError

    def read(self) -> SensorReading:
        """One reading. Raises SensorError rather than guessing."""
        raise NotImplementedError

    def read_many(self, count: int, *, interval: float = 0.0) -> list[SensorReading]:
        """`count` readings. Backends with a native burst mode override this."""
        if count < 1:
            raise SensorError("Ask for at least one reading")
        readings = []
        for index in range(count):
            if interval and index:
                time.sleep(interval)
            readings.append(self.read())
        return readings

    def stream(self, count: int) -> Iterator[SensorReading]:
        for _ in range(max(0, count)):
            yield self.read()

    def require_available(self) -> None:
        usable, reason = self.available()
        if not usable:
            raise SensorError(f"{self.name} is not available: {reason}")


class MockCartSensor(SensorBackend):
    """A cart on a track, generated from x(t) = x0 + v0·t + ½·a·t².

    Always reports `simulated = True`. The flag is a class attribute and the
    constructor takes no option to change it, because the whole risk this class
    carries is that its output is indistinguishable from real data by eye.

    `noise` adds Gaussian scatter so the data is not suspiciously perfect; it
    is seeded, so a run is reproducible and a test can assert exact values.
    """

    name = "mock.cart.position"
    simulated = True

    def __init__(
        self,
        *,
        initial_position: float = 0.0,
        initial_velocity: float = 1.0,
        acceleration: float = 0.1,
        interval: float = 1.0,
        noise: float = 0.0,
        uncertainty: float | None = 0.01,
        unit: str = "m",
        seed: int | None = 1729,
        start_time: float = 0.0,
    ):
        self.initial_position = float(initial_position)
        self.initial_velocity = float(initial_velocity)
        self.acceleration = float(acceleration)
        self.interval = float(interval)
        if self.interval <= 0:
            raise SensorError("Sampling interval must be positive")
        self.noise = abs(float(noise))
        self.uncertainty = uncertainty
        self.unit = unit
        parse_unit(unit)
        self.start_time = float(start_time)
        self._random = random.Random(seed)
        self._step = 0

    # Interface ---------------------------------------------------------------
    def available(self) -> tuple[bool, str]:
        return True, "Simulated cart; no hardware required."

    def describe(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "simulated": True,
            "quantities": ["time", "position"],
            "unit": self.unit,
            "model": "x(t) = x0 + v0*t + 0.5*a*t^2",
            "parameters": {
                "x0": self.initial_position,
                "v0": self.initial_velocity,
                "a": self.acceleration,
                "interval_s": self.interval,
                "noise_sigma": self.noise,
            },
            "warning": (
                "This backend generates data from an equation. Its output is not "
                "a measurement of anything and must never be reported as one."
            ),
        }

    def position_at(self, t: float) -> float:
        """The noiseless model value, for tests and for plotting the ideal."""
        return (self.initial_position
                + self.initial_velocity * t
                + 0.5 * self.acceleration * t * t)

    def read(self) -> SensorReading:
        t = self.start_time + self._step * self.interval
        self._step += 1
        value = self.position_at(t)
        if self.noise:
            value += self._random.gauss(0.0, self.noise)
        return SensorReading(
            quantity="position",
            value=value,
            unit=self.unit,
            uncertainty=self.uncertainty,
            timestamp=t,
            sensor_id=self.name,
            simulated=True,
            metadata={"model_time_s": t, "noiseless_value": self.position_at(t)},
        )

    def reset(self) -> None:
        self._step = 0

    def sample(self, count: int) -> tuple[list[SensorReading], list[SensorReading]]:
        """A paired time/position run, the shape the motion engine wants.

        Returns (time readings, position readings). The time readings are
        simulated too: in a real run the clock is part of the apparatus, and
        pretending its values are measured while the positions are not would
        be its own small lie.
        """
        positions = self.read_many(count)
        times = [
            SensorReading(
                quantity="time",
                value=reading.timestamp,
                unit="s",
                uncertainty=0.0 if self.noise == 0 else None,
                timestamp=reading.timestamp,
                sensor_id=self.name,
                simulated=True,
                metadata={"model_time_s": reading.timestamp},
            )
            for reading in positions
        ]
        return times, positions


class StaticSensor(SensorBackend):
    """Replays a fixed list of readings. For tests and for importing a file.

    `simulated` is a constructor argument here because the caller genuinely
    knows: replaying a CSV exported from a real run is not simulated data, and
    replaying numbers someone made up is. It defaults to True, so forgetting to
    say produces the cautious answer.
    """

    def __init__(self, readings: Sequence[SensorReading], *, name: str = "static",
                 simulated: bool = True):
        self.name = name
        self.simulated = bool(simulated)
        self._readings = list(readings)
        self._index = 0

    def available(self) -> tuple[bool, str]:
        remaining = len(self._readings) - self._index
        return remaining > 0, f"{remaining} readings remaining"

    def describe(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "simulated": self.simulated,
            "count": len(self._readings),
            "quantities": sorted({r.quantity for r in self._readings}),
        }

    def read(self) -> SensorReading:
        if self._index >= len(self._readings):
            raise SensorError(f"{self.name} has no readings left")
        reading = self._readings[self._index]
        self._index += 1
        return reading


def rms_error(readings: Sequence[SensorReading], expected: Sequence[float]) -> float:
    """Root-mean-square difference between readings and expected values.

    Used to check that a noisy generator stays near its model. It is a
    diagnostic, not a goodness-of-fit test for real data.
    """
    if len(readings) != len(expected):
        raise SensorError("Need one expected value per reading")
    if not readings:
        return 0.0
    total = sum((r.value - e) ** 2 for r, e in zip(readings, expected))
    return math.sqrt(total / len(readings))
